### ISSUE TITLE
Action Center Windows 10 toast title

### ISSUE THREAD

**Issue by paulbeliavskisPanviva** [mikaelbr/node-notifier#135]
Running on windows 10, is it possible to customize the heading of your notifications produced by your app in the action center. Right now I see the heading toast. I have attached a photo. The notification has been created with the following code.

     notifier.notify({
        title: 'My awesome title',
        message: 'Hello from node, Mr User!',
        icon: __dirname + '/notification_warning.png',
        sound: true,
        wait: true
    }, function(err, response){
        console.log(response);
    });

![actioncenter](https://cloud.githubusercontent.com/assets/20054969/17956596/7ab45726-6ace-11e6-815c-6f2fd4b56ae0.png)

**Comment by kurisubrooks** [comment]
The only way to circumvent this would be to change the `toast.exe` executable itself, rename it, and then specify it manually in node-notifier (found in the notifiers folder). 

Otherwise there is nothing else that we can do to make this programatically change in terms of our API. This is just how notifications on these kind of systems work.
