### ISSUE TITLE
WTF is this zzz icon in the notification?

### ISSUE THREAD

**Issue by jochemstoel** [mikaelbr/node-notifier#157]
This package is perfect but what the hell is that black and white icon in each notification and more importantly, how do I get rid of it?

![zzz icon](http://i64.tinypic.com/23lxw05.png)

**Comment by kurisubrooks** [comment]
Interesting, does this get removed when you specify your own `image`?

**Comment by jochemstoel** [comment]
No, when I add my own image, it is displayed on the left side of the notification. The zzz image on the right is still there. I am using Windows Server 2012  and I am pretty sure this image is not a server user avatar or anything like that.

**Comment by MadLittleMods** [comment]
@jochemstoel Snoretoast, https://github.com/KDE/snoretoast/blob/master/data/zzz.ico

**Comment by mavrick** [comment]
I'm getting the same issue on windows 10 and i also specify the image attribute

**Comment by jochemstoel** [comment]
Okay @MadLittleMods  so why is it in my notification?

**Comment by kurisubrooks** [comment]
@jochemstoel The reason the icon appears is because we use SnoreToast as the Executable to spawn notifications on Windows. Unfortunately, this isn't really a bug, but rather how Windows works. This also happens on macOS, with the way Notifications are displayed. As this is an upstream issue there's not much we can do about it, but if you wish to remove it, you can build SnoreToast on your own and replace that .ico file @MadLittleMods referenced above with an .ico that you do want in it's place.

**Comment by s-KaiNet** [comment]
@kurisubrooks do you have any samples how to build SnoreToast to replace those .ico?
