### ISSUE TITLE
Error: net.connect is not a function

### ISSUE THREAD

**Issue by adnan358** [mikaelbr/node-notifier#162]
I'm installed package last night but  i did not use notifier.

I use that code

```
const notifier = require('node-notifier');
notifier.notify('Message');
```

Im getting error below 
```
net.connect is not a function
at module.exports (bundle.js:25477)
at Growl.notify
```

Please help me, Thanks

**Comment by kurisubrooks** [comment]
Hi, what OS and version are you using currently?

On 23 Mar. 2017 6:46 am, "adnan358" <notifications@github.com> wrote:

I'm installed package last night but i did not use notifier.

I use that code

const notifier = require('node-notifier');
notifier.notify('Message');

Im getting error below

net.connect is not a function
at module.exports (bundle.js:25477)
at Growl.notify

Please help me, Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mikaelbr/node-notifier/issues/162>, or mute the thread

**Comment by mikaelbr** [comment]
This seems like being run from Webpack or something similar? Inside either electron or on a page. In any case, node-notifier needs to be run in a node-context, having access to child processes.

**Comment by scris** [comment]
Win 8.1 
Node 10.11.0
Electron 5.0.6 (electron-packager)
Node-Notifier 5.4.0
The same issue, could you please send a more detailed solution?
Thanks.

**Comment by paddotk** [comment]
So this issue is closed but I'm not seeing any solutions. I am using v8.0.0 in Electron and am having the same problem, how do I resolve this?

**Comment by SRichner** [comment]
@mikaelbr We're having the same issue, using Electron v11.

@paddotk did you manage to get this working?
