### ISSUE TITLE
Cannot read property 'customPath' of undefined

### ISSUE THREAD

**Issue by stevenvachon** [mikaelbr/node-notifier#174]
```js
const {notify} = require('node-notifier');
notify('um');
```

```
TypeError: Cannot read property 'customPath' of undefined
       at NotificationCenter.notify (/project/node_modules/node-notifier/notifiers/notificationcenter.js:88:19)
```

It even fails with the destructuring removed:
```js
const notify = require('node-notifier').notify;
```

It only works if done this way:
```js
const notifier = require('node-notifier');
notifier.notify('um');
```

---

It's fixed if I change all instances of `this.options` in the above file to `options`, but I can't submit a nice PR for this as the test cannot run on Node.js versions < 6.

**Comment by aduh95** [comment]
The same problem occurs when using [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original).

This raises the TypeError `Cannot read property 'customPath' of undefined`:

```js
const { WindowsToaster } = require("node-notifier");
const sendNotification = require("util").promisify(new WindowsToaster().notify);
sendNotification("Hello")
  .then(result => console.log(result))
  .catch(err => console.error(err));
```

This as well:

```js
const sendNotification = require("util").promisify(
  require("node-notifier").notify
);
sendNotification("Hello")
  .then(result => console.log(result))
  .catch(err => console.error(err));
```

But this works:

```js
const { WindowsToaster } = require("node-notifier");
new WindowsToaster().notify("Hello", (err, result) => {
  err ? console.error(err) : console.log(result)
});
```

**Comment by mikaelbr** [comment]
This is due to the node-notifier being implemented as a constructor function, and by destructuring the notify "method" you essentially remove it from it context and `this` will no longer work.

It is the same as the following:

```
var someObj = {
  foo: 'Hello, World!',
  logFoo: function () {
    console.log(this.foo);
  }
};

someObj.logFoo(); //=> Logs "Hello, World!" as we are on the someObj context

var log = someObject.logFoo; // => detaches it from the context
log(); //=> Logs "undefined" as we no longer are attached to the context/this
```

It's the same case with promesify. Detaching the notify "method" from the context. It's just how JavaScript works with contexts and "classes" (that is newed up objects with prototype functions).

Had I rewritten node-notifier entirely now, I would use a different approach with closures instead of context, but that's a major rewrite and not one I'm prioritising right now. But it's something I want to do and hopefully will happen in the future.

Hope the explanation makes sense.

**Comment by aduh95** [comment]
Thanks @mikaelbr, it makes sense now!

As I found out, I can use promises if I bind the context back to node-notifier:

```js
const notifier = require("node-notifier");
const sendNotification = require("util").promisify(
  notifier.notify.bind(notifier)
);
sendNotification("Hello") // Works as expected
  .then(result => console.log(result))
  .catch(err => console.error(err));
```

I'll let that here in case anyone else encounters the same issue.
