### ISSUE TITLE
Please update terminal-notifier

### ISSUE THREAD

**Issue by sophistifunk** [mikaelbr/node-notifier#183]
It's got a serious [memory leak](https://github.com/julienXX/terminal-notifier/issues/173)

**Comment by mikaelbr** [comment]
I've been holding out (there is kind of a workaround in node-notifier for the memory leak) on updating due to some changes in the way icons are handled, and haven't found a good enough way to distribute ability to customize icons. The latest version is in master now if you want to test it out and check that it doesn't break any of your existing behaviour.

**Comment by charleskoehl** [comment]
[Apparently the leak is fixed in v 1.7.2](https://github.com/julienXX/terminal-notifier/issues/173#issuecomment-301106136)

**Comment by mikaelbr** [comment]
Done in 5.2.1
