### ISSUE TITLE
[Question] How does Node.js load binary file work?

### ISSUE THREAD

**Issue by luokuning** [mikaelbr/node-notifier#196]
Hi there, I am really impressed by this project, thanks for your job. 

Now I am a bit confused about the code that **how can Node.js load binary file?**

```javascript
var notifier = path.join(
  __dirname,
  '../vendor/terminal-notifier'
);
```

As I notice that `../vendor/terminal-notifier` is a binary file, and [terminal-notifier](https://github.com/julienXX/terminal-notifier) even write in Objective-c, so how can they work together?

Any response will be appreciated 😄

**Comment by mikaelbr** [comment]
This particular code just resolves pathing to point to the binary by full path. `path.join` concats two path strings with the system specific separator, and __dirname is a "magic" injected with the full absolute path to the directory where the particular .js file is located.

What actually executes the binary is this module: https://nodejs.org/api/child_process.html
Spinning up a child process by referencing a new process. Much like fork in C, but instead of a new process of yourself, you do it with another process.

**Comment by luokuning** [comment]
Solved all my puzzles, thank you 😸

**Comment by mikaelbr** [comment]
No worries. Happy to clarify.
