### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by okuryu** [mikaelbr/node-notifier#198]
Several changes are not available on npm registry.
https://github.com/mikaelbr/node-notifier/compare/v5.1.2...master

Could you publish a new version of node-notifier? I think v5.2.0 is better on the basis of dependencies updates.

**Comment by mikaelbr** [comment]
Hi, sorry for the late response. There's been some changes in the terminal-notifier dependency and I'm not quite sure how to best set icon now, so I'm afraid it might be a breaking change. I will need people who use custom icons in their electron apps or what ever to test and verify that the master branch still works.

**Comment by rfieve** [comment]
Hello @mikaelbr ,

What about publishing a 5.1.3 fix version to npm with at least the bellow picked commit?
For now, people using any process.env.DEBUG will be notified with your logs too.
To avoid this behavior, we now have to reference your package from git instead of npm.
What do you think?
Related commit: https://github.com/mikaelbr/node-notifier/commit/00b6984f5b6efd98474cc4d7cc49b5de38646d5d#diff-50e3aa130a4f97a42ee2cf111c7b1d9d

**Comment by mikaelbr** [comment]
Done. 5.2.1 is out now.
