### ISSUE TITLE
snoreToast is having GPL license , it's affecting audit of our release even-though it is devDependencies 

### ISSUE THREAD

**Issue by skybitsindri** [mikaelbr/node-notifier#275]

**Comment by sashankaryal** [comment]
Any updates? We're not getting to use it in our company because of it as well. The worst thing is "react-scripts" depends on it as well.

**Comment by mikaelbr** [comment]
Hi. snoreToast uses a LGPL License, not straight up GPL. Also, this to me looks like a problem with the auditing more than snoreToasts license?

As this is a devDependency as far as I know, there isn't anything in the license preventing you to use a tool of GPL to make software. This would be like if you weren't allowed to use Gimp to make icons.

**Comment by aldo-roman** [comment]
@mikaelbr yeah, but auditing processes tend to be automated, and explaining exceptions to security teams never straightforward. Also, it is true for devDependency, but once a library has been "permitted", anyone on a company can potentially use it and distribute, breaking the license.

Best way to get your package into companies is to use MIT.

Any chance we can see a license change?

**Comment by mikaelbr** [comment]
Hi again. Just for the record, snoreToast is a dependency of this project so (unfortunately perhaps) I don't have any control over the license. Honestly I doubt it will change.

Also I think you'll find a lot of different opinions on permissive licenses and how this is managed. I don't have any wish to actively recruit companies to use my package, or to pursue a scenario there everything is permissive license so companies can use it without thinking about licenses other than "just getting things for free while they make money". It seems like you say `Best way to get your package into companies is to use MIT` as if it is some sort of reward.

Please take a time to consider what you are actually asking here. You are asking someone using their time to make something and giving it away for free to do a major change just so that companies don't have to actively think about licenses while making money on the works of others. Also, it is actually free to use, and pretty permissive, but it's "kind of a hassle" because of some internal corporate processes. I'm sorry if I seem harsh here, but I'm not interested in fixing your internal politics.
