### ISSUE TITLE
webpack and node-notifier

### ISSUE THREAD

**Issue by jmc420** [mikaelbr/node-notifier#94]
Hi

I have been using node-notifier in an electron app and it works fine until I use webpack to concatenate everything into a single file.

there are 2 issues:

1. semver version

Could you upgrade the version of semver in package.json to "semver": "^5.1.0".

Using the earlier version of semver causes a problem when you use webpack:

https://github.com/webpack/webpack/issues/1942

I can stop this problem if I locally upgrade the node-notifier semver version.

2. notifications stop when using webpack version because it calculates the location of teminal-notifier-app incorrectly.

I guess this is similar to the electron asar problem that you mention in the main README. 

This line of code:

notifier = path.join(__dirname, '../vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier'),
	  
gets the wrong path. __dirname points to the directory of the webpack bundled js file and so it does not find node_modules/node-notifier/vendor directory correctly. I guess the simplest solution is just to copy the vendor directory into location ../vendor relative to the webpack bundle.

**Comment by kurisubrooks** [comment]
We'll look into this for you.

**Comment by kurisubrooks** [comment]
From #73 
>@mikaelbr: I think all the major updates are good. However, I don't see why the minor ranges should be bumped. This causes less packages to be deduped by npm as it's more restrictive. As a rule of thumb, I try to have the version ranges as forgiving as possible, allowing for more deduping.

>@mikaelbr: Yeah, node-notifier will probably run just fine, but the problem is if we have too small window of dependency versions, we will possibly cause our consumers to have some duplicate packages. Also, there is rarely any need to bump major release, unless a major release introduces a feature we want to use / are dependent on.

**Comment by mikaelbr** [comment]
We can easily bump to new semver version as it has some new features that can be nice to have (better support for browser usage is a feature too).

I'm more skeptical about the second issue using `__dirname`. This feels like a problem of WebPack, not `node-notifier`. Surely other packages also use `__dirname` with it's expected behaviour. Have you tried activating something like:

```
node: {
  __dirname: true
}
```

in the Webpack config?

**Comment by jmc420** [comment]
On the second issue, yes thanks for pointing out the __dirname configuration solution. 

As regards the first issue, as far as I can tell webpack2 thinks semver 4.1.0 is an AMD module and it prefixes and suffixes it with __WEBPACK code which causes a runtime error.  webpack does not do this with semver 5.1.0. If I comment out the _WEBPACK code where semver 4.1.0 has been bundled, it also works. Not quite sure whether kurlsubrooke sees this as a bug in webpack or not - it is obviously not a bug in node-notifier itself. There must be lots of other packages which use semver.

If they decide it is not an issue, bumping the semver version in node-notifier would be great.

**Comment by mikaelbr** [comment]
I've updated the semver dependency now. You can test it out by doing `npm i mikaelbr/node-notifier`.

**Comment by jmc420** [comment]
thanks that will be fine.

when will you add it as a versioned release which I can reference in my
package.json?

**Comment by jaulz** [comment]
I tried that version from @mikaelbr but still I get the error `Uncaught TypeError: Invalid Version: function (request) ...`
@jmc420 do I need to consider something else when installing that version or how did you manage to get that up and running?

Thank you both!

**Comment by kurisubrooks** [comment]
@jaulz Could we please have the full stack trace?

**Comment by jaulz** [comment]
Not sure how I can format the strack trace better but basically here it is. Though it is anyway a bit cryptic because of webpack:

``
Uncaught TypeError: Invalid Version: function (request) {
/******/ 			if(me.hot.active) {
/******/ 				if(installedModules[request]) {
/******/ 					if(installedModules[request].parents.indexOf(moduleId) < 0)
/******/ 						installedModules[request].parents.push(moduleId);
/******/ 					if(me.children.indexOf(request) < 0)
/******/ 						me.children.push(request);
/******/ 				} else hotCurrentParents = [moduleId];
/******/ 			} else {
/******/ 				console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
/******/ 				hotCurrentParents = [];
/******/ 			}
/******/ 			return __webpack_require__(request);
/******/ 		}SemVer @ semver.browser.js?9f22:271define.function.define.amd.semver @ semver.browser.js?9f22:1195(anonymous function) @ semver.browser.js?9f22:1197(anonymous function) @ bundle.js:5594__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ utils.js?0806:6(anonymous function) @ bundle.js:5564__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ index.js?db00:2(anonymous function) @ bundle.js:5552__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ notifier.js?896c:7(anonymous function) @ bundle.js:5546__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM631:43(anonymous function) @ Tab.js?3f1e:142(anonymous function) @ bundle.js:5516__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM630:11(anonymous function) @ bundle.js:5510__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM624:35(anonymous function) @ Tabs.js?1997:46(anonymous function) @ bundle.js:5480__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM623:11(anonymous function) @ bundle.js:5474__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM333:21(anonymous function) @ bundle.js:2006__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ VM102:13(anonymous function) @ bundle.js:602__webpack_require__ @ bundle.js:522fn @ bundle.js:77(anonymous function) @ bundle.js:553__webpack_require__ @ bundle.js:522(anonymous function) @ bundle.js:545(anonymous function) @ bundle.js:548
``

**Comment by jmc420** [comment]
@jaulz assuming you have top level package.json that references node-notifier, cd into node_modules/node_notifier and edit package.json so that semver is ^5.1.0. Save the file and then run npm install in that location. 

Go back to your top level directory and run your webpack command. The Invalid version problem should go away. Also check that semver within your webpack bundle does not include the lines:

if (true)
  !(__WEBPACK_AMD_DEFINE_FACTORY__ = (exports), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.call(exports, __webpack_require__, exports, module)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));

see https://github.com/webpack/webpack/issues/1942

**Comment by jmc420** [comment]
could you release the update to semver version in package.json into a new node-notifier release (4.4.1?) so that it works with webpack?

**Comment by mikaelbr** [comment]
```
➜  node-notifier git:(master) npm publish
+ node-notifier@4.5.0
```

:cake:

**Comment by mikaelbr** [comment]
I consider this closed now. If theres any problems, it can be re-opened or just add a new issue.

**Comment by jaulz** [comment]
Yep, many thanks :)
